#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Interactive API Keys Setup
"""

import os
import sys
from pathlib import Path

def setup_api_key(key_name, description, website):
    """Thiet lap API key"""
    print(f"\n{key_name}:")
    print(f"Mo ta: {description}")
    print(f"Website: {website}")
    
    current_value = os.getenv(key_name, "")
    if current_value:
        masked_value = current_value[:10] + "..." if len(current_value) > 10 else current_value
        print(f"Hien tai: {masked_value}")
        update = input("Ban co muon cap nhat? (y/n): ").lower().strip()
        if update != 'y':
            return current_value
    
    api_key = input(f"Nhap {key_name}: ").strip()
    if api_key:
        return api_key
    else:
        print("Bo qua...")
        return current_value

def save_to_env(api_keys):
    """Luu API keys vao file .env"""
    env_content = """# API Keys for Video Generation System
# Generated by setup_api_keys.py

# REQUIRED APIs
"""
    
    required_keys = ["PEXELS_API_KEY", "ELEVENLABS_API_KEY", "GEMINI_API_KEY"]
    optional_keys = ["UNSPLASH_ACCESS_KEY", "OPENAI_API_KEY", "STABILITY_API_KEY"]
    
    for key in required_keys:
        if key in api_keys and api_keys[key]:
            env_content += f"{key}={api_keys[key]}\n"
        else:
            env_content += f"# {key}=your_{key.lower()}_here\n"
    
    env_content += "\n# OPTIONAL APIs\n"
    for key in optional_keys:
        if key in api_keys and api_keys[key]:
            env_content += f"{key}={api_keys[key]}\n"
        else:
            env_content += f"# {key}=your_{key.lower()}_here\n"
    
    env_content += "\n# Settings\nREQUIRE_HUMAN_VOICE=1\n"
    
    try:
        with open(".env", "w", encoding="utf-8") as f:
            f.write(env_content)
        print("\nDA LUU VAO FILE .env")
        return True
    except Exception as e:
        print(f"\nLOI LUU FILE: {e}")
        return False

def test_api_keys(api_keys):
    """Test API keys"""
    print("\nKIEM TRA API KEYS:")
    print("-" * 40)
    
    # Test Pexels
    if api_keys.get("PEXELS_API_KEY"):
        try:
            import requests
            headers = {"Authorization": api_keys["PEXELS_API_KEY"]}
            response = requests.get(
                "https://api.pexels.com/v1/search",
                params={"query": "test", "per_page": 1},
                headers=headers,
                timeout=10
            )
            if response.status_code == 200:
                print("PEXELS: OK")
            else:
                print(f"PEXELS: LOI ({response.status_code})")
        except Exception as e:
            print(f"PEXELS: LOI ({e})")
    else:
        print("PEXELS: CHUA CO")
    
    # Test ElevenLabs
    if api_keys.get("ELEVENLABS_API_KEY"):
        try:
            import requests
            headers = {"xi-api-key": api_keys["ELEVENLABS_API_KEY"]}
            response = requests.get(
                "https://api.elevenlabs.io/v1/voices",
                headers=headers,
                timeout=10
            )
            if response.status_code == 200:
                print("ELEVENLABS: OK")
            else:
                print(f"ELEVENLABS: LOI ({response.status_code})")
        except Exception as e:
            print(f"ELEVENLABS: LOI ({e})")
    else:
        print("ELEVENLABS: CHUA CO")
    
    # Test Gemini
    if api_keys.get("GEMINI_API_KEY"):
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_keys["GEMINI_API_KEY"])
            model = genai.GenerativeModel("gemini-2.5-flash")
            response = model.generate_content("Test")
            if response.text:
                print("GEMINI: OK")
            else:
                print("GEMINI: LOI")
        except Exception as e:
            print(f"GEMINI: LOI ({e})")
    else:
        print("GEMINI: CHUA CO")

def main():
    """Main function"""
    print("=" * 60)
    print("THIET LAP API KEYS CHO HE THONG TAO VIDEO")
    print("=" * 60)
    
    print("\nCAC API KEYS BAT BUOC:")
    print("1. PEXELS_API_KEY - Tim hinh anh phu hop voi noi dung")
    print("2. ELEVENLABS_API_KEY - Tao giong nguoi that")
    print("3. GEMINI_API_KEY - Phan tich noi dung va tao cau truc")
    
    print("\nCAC API KEYS TUY CHON:")
    print("4. UNSPLASH_ACCESS_KEY - Backup cho hinh anh")
    print("5. OPENAI_API_KEY - Tao hinh anh bang AI")
    print("6. STABILITY_API_KEY - Tao hinh anh bang AI")
    
    # Load existing .env
    env_file = Path(".env")
    if env_file.exists():
        try:
            with open(env_file, 'r', encoding='utf-8') as f:
                for line in f:
                    if '=' in line and not line.startswith('#'):
                        key, value = line.strip().split('=', 1)
                        os.environ[key] = value
        except Exception as e:
            print(f"Loi doc file .env: {e}")
    
    api_keys = {}
    
    # Setup required APIs
    print("\n" + "=" * 40)
    print("THIET LAP API KEYS BAT BUOC")
    print("=" * 40)
    
    api_keys["PEXELS_API_KEY"] = setup_api_key(
        "PEXELS_API_KEY",
        "Tim hinh anh chat luong cao",
        "https://www.pexels.com/api/"
    )
    
    api_keys["ELEVENLABS_API_KEY"] = setup_api_key(
        "ELEVENLABS_API_KEY", 
        "Tao giong nguoi that tu nhien",
        "https://elevenlabs.io/"
    )
    
    api_keys["GEMINI_API_KEY"] = setup_api_key(
        "GEMINI_API_KEY",
        "Phan tich noi dung va tao cau truc bai giang", 
        "https://aistudio.google.com/app/apikey"
    )
    
    # Setup optional APIs
    print("\n" + "=" * 40)
    print("THIET LAP API KEYS TUY CHON")
    print("=" * 40)
    
    setup_optional = input("Ban co muon thiet lap API keys tuy chon? (y/n): ").lower().strip()
    if setup_optional == 'y':
        api_keys["UNSPLASH_ACCESS_KEY"] = setup_api_key(
            "UNSPLASH_ACCESS_KEY",
            "Backup cho tim hinh anh",
            "https://unsplash.com/developers"
        )
        
        api_keys["OPENAI_API_KEY"] = setup_api_key(
            "OPENAI_API_KEY",
            "Tao hinh anh bang AI",
            "https://platform.openai.com/api-keys"
        )
        
        api_keys["STABILITY_API_KEY"] = setup_api_key(
            "STABILITY_API_KEY",
            "Tao hinh anh bang AI",
            "https://platform.stability.ai/"
        )
    
    # Save to .env
    if save_to_env(api_keys):
        print("\n" + "=" * 40)
        print("KET QUA")
        print("=" * 40)
        
        # Test API keys
        test_api_keys(api_keys)
        
        print("\n" + "=" * 40)
        print("HOAN THANH!")
        print("=" * 40)
        print("Ban co the:")
        print("1. Chay: python test_image_matching.py")
        print("2. Tao video tu ung dung web")
        print("3. Kiem tra chat luong hinh anh va giong noi")
    else:
        print("\nLOI: Khong the luu file .env")

if __name__ == "__main__":
    main()
